### ISSUE TITLE
multiple laravel queue workers

### ISSUE THREAD

**Issue by warroyo** [pafelin/laravel-gearman#4]
I currently have laravel-gearman working, but is there a way to run multiple laravel Queue:work  as gearman workers?

**Comment by pafelin** [comment]
when you run 
```
php artisan queue:listen
```
that starts a worker ( 1 worker) . Depending on your set up you can run multiple times this command if you need more workers. I am using supervisord, so in my supervisord I set that the command have to be running 5 times. In that way i always have 5 workers up and running.

if you need some help you can put a comment here
