### ISSUE TITLE
[ReflectionException] Class TaskProcess\Services\SendMail does not exist

### ISSUE THREAD

**Issue by dereckmartin** [pafelin/laravel-gearman#5]
I have setup this up per the README.md on L4.2.  When I push to the queue, I see the queue grow in gearadmin --status.  However the tasks always fail.  Running artisan queue:work shows this:

![screenshot 2015-03-11 01 36 21](https://cloud.githubusercontent.com/assets/5254148/6590954/475e9e1a-c78f-11e4-918c-5b62d35e0cdf.png)

This is the directory where the SendEmail class is located.

    ls -l app/service/
    total 8
    -rw-r--r-- 1 vagrant vagrant 327 Mar 11 05:21 GearmanTest.php
    -rw-r--r-- 1 vagrant vagrant 487 Mar 11 05:29 SendMail.php

Is there something missing from the docs that I do not see.

**Comment by dereckmartin** [comment]
Well, I don't know the issue.  However, adding app/service to the composer autoload classmaps and running autodump allowed the class to be found, and appears to have solved my particular problem.

**Comment by pafelin** [comment]
the sendmail service was just part of the example. You can put any class you want as a handler of the job
