### ISSUE TITLE
Laravel 5 doesn't use QueueInterface

### ISSUE THREAD

**Issue by marcolumia** [pafelin/laravel-gearman#9]
GearmanQueue uses QueueInterface that isn't available in laravel 5 anymore. The new class and namespace is 'Illuminate\Contracts\Queue\Queue'

I forked the repo, and will send off a pull request for this later tonight.

**Comment by dereckmartin** [comment]
What is the solution to resolve this?

**Comment by dereckmartin** [comment]
Nevermind, I think I figured it out.

use Illuminate\Contracts\Queue\Queue as QueueInterface;

**Comment by pafelin** [comment]
if you can put it as a pull request we can merge it in another branch. It would be great

**Comment by michabbb** [comment]
is there a repo/fork now for laravel 5 ?
